# -*- coding: utf-8 -*-
"""rag_system.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wBvuHHqRBzE1J3nWHHkpAdQ5HCx2JIxT
"""

import os
from dotenv import load_dotenv

# Load variables from the .env file
load_dotenv()

# Fetch the keys securely
openai_api_key = os.getenv("OPENAI_API_KEY")
huggingface_api_key = os.getenv("HUGGINGFACE_API_KEY")

#necessary libaries
from youtube_transcript_api import YouTubeTranscriptApi, TranscriptsDisabled
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain_huggingface import ChatHuggingFace, HuggingFaceEndpoint , HuggingFaceEmbeddings
from langchain_community.vectorstores import FAISS
from langchain_core.prompts import PromptTemplate

#here we are fetching the transcript from the yt vedio

video_id = "ShYKkPPhOoc" # id of the youtube vedio
try:
    transcript_list = YouTubeTranscriptApi.get_transcript(video_id, languages=["en"])#choose language of the transcript

    #printing the orignal list containg text , time and duration
    print(transcript_list)
    # flatting the transcript
    transcript = " ".join(item["text"] for item in transcript_list)
    print(transcript)

except TranscriptsDisabled:
    print("No captions available for this video.")

#now we have to split the transcript in to smaller chunks
splitter = RecursiveCharacterTextSplitter(chunk_size=1000, chunk_overlap=200)
chunks = splitter.create_documents([transcript])

print(len(chunks))

print(chunks[0].page_content)

model_name = "sentence-transformers/all-MiniLM-L6-v2"

embeddings = HuggingFaceEmbeddings(
    model_name=model_name,
    model_kwargs={'device': 'cpu'},
    encode_kwargs={'normalize_embeddings': True}
)
vector_store = FAISS.from_documents(chunks, embeddings)

#viewing the embeddings
vector_store.index_to_docstore_id

#veiwing a document
vector_store.get_by_ids(['d12c3585-b977-4bf5-a8a1-9fc35463cf4b'])

#now making a retriver that will retrive the relevent document from the documents that we have created in previous step
retriever = vector_store.as_retriever(search_type="mmr", search_kwargs={"k": 3})

#making a query
retriever.invoke("what is this vedio for")

llm_huggingface = HuggingFaceEndpoint(
    repo_id="mistralai/Mistral-7B-Instruct-v0.2",
    task="text-generation",
    temperature=0.1,
    max_new_tokens=100,
    timeout=120
)

model = ChatHuggingFace(llm=llm_huggingface)

prompt = PromptTemplate(
    template="""
      You are a helpful ai assistant.
      answer only from the provided transcript context.
      If the context is insufficient, just say you don't know.

      {context}
      Question: {question}
    """,
    input_variables = ['context', 'question']
)

question = "how to spend our 20 in ai era"
retrived_doc = retriever.invoke(question , k = 3)

retrived_doc

context = "  ".join(retrived_doc.page_content for retrived_doc in retrived_doc)

context

final_prompt = prompt.invoke({'context': context , 'question': question })

final_prompt

result = model.invoke(final_prompt)

print(result.content)

"""doing this through chains"""

from langchain_core.runnables import RunnableParallel , RunnableSequence , RunnablePassthrough , RunnableLambda
from langchain_core.output_parsers import StrOutputParser

def format_doc(retrived_doc):
  context_doc = " ".join(retrived_doc.page_content for retrived_doc in retrived_doc)
  return context_doc

parallel_chain = RunnableParallel({
    'context' : retriever | RunnableLambda(format_doc),
    'question' : RunnablePassthrough()
})

parallel_chain.invoke("who is speaking in the vedio")

parser = StrOutputParser()

final_chain = parallel_chain | prompt | model | parser

final_chain.invoke('summarize the vedio')

