# -*- coding: utf-8 -*-
"""toolwithllm.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12IatBTAGRuSDat1RfDeLMzvRmlxTenaC
"""

import os
from dotenv import load_dotenv

# Load variables from the .env file
load_dotenv()

# Fetch the keys securely
openai_api_key = os.getenv("OPENAI_API_KEY")
huggingface_api_key = os.getenv("HUGGINGFACE_API_KEY")
from huggingface_hub import login
login()



from langchain_huggingface import HuggingFaceEndpoint , ChatHuggingFace
from langchain_core.tools import tool
from langchain_core.messages import HumanMessage
import requests

@tool
def multiply(a: int , b: int) -> int:
  "multiplying two nbrs"
  return a*b

print(multiply.invoke({'a':3, 'b':4}))

llm = HuggingFaceEndpoint(
    repo_id = "mistralai/Mistral-7B-Instruct-v0.2"
)

model = ChatHuggingFace(llm=llm)

model.invoke("hi")

BindingToolWithLlm = model.bind_tools([multiply])

BindingToolWithLlm.invoke("hi")

query = HumanMessage(" can you multiplt 2 * 20343 do not do this yourself instead check for a tool i binded with u")

message = [query]

message

result =BindingToolWithLlm.invoke(message)

message.append(result)

message

