# -*- coding: utf-8 -*-
"""tools.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rP46_YJXZglx8bHylJzw-ioinqGc6dxp
"""

!pip install langchain langchain-core langchain-community pydantic duckduckgo-search

!pip install ddgs

"""DUCKDUCKSEARCHRUN TOOL"""

from langchain_community.tools import DuckDuckGoSearchRun

# Initialize the search engine
search_engine = DuckDuckGoSearchRun()

# Invoke the search and store the result
# The 'result' variable will contain a string with the search results.
result = search_engine.invoke('top news in the pakistan today')

# Print the obtained result
print(result)

!pip install -qU langchain-azure-dynamic-sessions

"""Making our own tool"""

from langchain_core.tools import tool

#define the function
def addition(a , b):
  "this function is adding two numbers"
  return a+b

#step 2 - type hints
def addition(a: int  , b: int ) -> int:
  "this function is adding two numbers"
  return a+b

#add @tool

@tool
def addition(a , b):
  "this function is adding two numbers"
  return a+b

result = addition.invoke({'a':6,'b':7})
print(result)

print(addition.name)

print(addition.description)

print(addition.args_schema)

print(addition.args)

"""making a custom tool usinng pydantic"""

from langchain.tools import StructuredTool
from pydantic import BaseModel , Field

from typing_extensions import Required
from dataclasses import field
def input_schema(BaseModel):
  a: int = Field(Required =True , description = "first nbr to add "),
  b: int = Field(Required =True , description = "second nbr to add")

def multiply_nbr(a: int , b: int  )->int :
  return a*b

from os import name
tool = StructuredTool.from_function(
    func = multiply_nbr,
    name ="multiplying",
    description = "this tool is used to multiply two numbers",
    input_schema = input_schema

)

result = tool.invoke({'a':5 , 'b':6})
print(result)

print(tool.name)

print(tool.description)

print(tool.args_schema)

print(tool.args)

"""using basetool class"""

from langchain.tools import BaseTool
from typing import Type

class MultiplyInput(BaseModel):
  a: int = Field(Required =True , description = "first nbr to add "),
  b: int = Field(Required =True , description = "second nbr to add")

class MultiplyTool(BaseTool):
    name: str = "multiply"
    description: str = "Multiply two numbers"

    args_schema: Type[BaseModel] = MultiplyInput

    def _run(self, a: int, b: int) -> int:
        return a * b

tool = MultiplyTool()

result = tool.invoke({'a': 5 , 'b':9})
print(result)

"""ToolKit"""

from langchain.tools import tool

@tool
def add(a: int, b: int)-> int:
  "add two nbrs"
  return a+b
@tool
def mul(a:int, b:int)-> int:
  "multiply two nbrs"
  return a*b

class mathkit:
  def gettools(self):
    return [add,mul]

tools = mathkit()

tools = object1.gettools()

for tool in tools:
  print(tool.name, "=>" ,tool.description, "\n" ,tool.invoke({'a':7 , 'b': 9}))

